/*
MySQL Data Transfer
Source Host: localhost
Source Database: mYnexia
Target Host: localhost
Target Database: mYnexia
Date: 8/25/2015 9:48:06 PM
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for Spells
-- ----------------------------
CREATE TABLE `Spells` (
  `SplId` int(10) unsigned NOT NULL,
  `SplIdentifier` varchar(32) NOT NULL DEFAULT '',
  `SplDescription` varchar(32) NOT NULL DEFAULT '',
  `SplType` int(10) unsigned NOT NULL DEFAULT '0',
  `SplPthId` int(10) unsigned NOT NULL DEFAULT '5',
  `SplQuestion` varchar(64) NOT NULL DEFAULT '',
  `SplDispel` int(10) unsigned NOT NULL DEFAULT '0',
  `SplAether` int(10) unsigned NOT NULL DEFAULT '0',
  `SplMute` int(10) unsigned NOT NULL DEFAULT '0',
  `SplActive` int(10) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`SplId`),
  KEY `SplPthId` (`SplPthId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `Spells` VALUES ('500', '      == Common ==', '      == Common ==', '0', '5', '      == Common ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('501', 'silver_thread', 'Silver Thread', '1', '0', 'Silver Thread (W/E)?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('502', 'gateway', 'Gateway', '1', '0', 'Gate Way (N/E/W/S)?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('503', 'appraise', 'Appraise', '8', '0', 'Inventory Slot: ?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('504', 'soothe', 'Soothe', '5', '0', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('505', 'fleshspeak', 'Fleshspeak', '5', '0', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('506', 'mentor', 'Mentor', '2', '0', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('507', 'respawn_sumo', 'Please wait...', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('508', 'invite', 'Invitation', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('509', 'sword_of_jujak', 'Jujak', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('510', 'sword_of_baekho', 'Baekho', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('511', 'sword_of_hyunmoo', 'Hyunmoo', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('512', 'sword_of_chungryong', 'Chungryong', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('513', '', '', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('514', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('515', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('516', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('517', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('518', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('519', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('520', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1000', '      == Warrior ==', '      == Warrior ==', '5', '5', '      == Warrior ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1001', 'wolf_fury', 'Wolf\'s Fury', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1002', 'tiger_fury', 'Tiger\'s Fury', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1003', 'dragon_fury', 'Dragon\'s Fury', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1004', 'soul_fly', 'Soul Fly', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1005', 'bless', 'Bless', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1006', 'backstab', 'Backstab', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1007', 'flank', 'Flank', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1008', 'relief', 'Relief', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1009', 'potence', 'Potence', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1010', 'enchant', 'Enchant', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1011', 'infuse', 'Infuse', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1012', 'ingress', 'Ingress', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1013', 'slash', 'Slash', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1014', 'berserk', 'Berserk', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1015', 'vigor', 'Vigor', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1016', 'champion_old', 'Champion Old', '1', '1', ':>', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1017', 'whirlwind', 'Whirlwind', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1018', 'fist_of_god', 'Fist of God', '5', '1', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1019', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1020', '           Barbarian', '           Barbarian', '5', '5', '           Barbarian', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1021', 'bear_might', 'Bear\'s Might', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1022', 'mount', 'Mount', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1023', 'push', 'Push', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1024', 'wilderness_guise', 'Wilderness Guise', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1025', 'bear_health', 'Bear\'s Health', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1026', 'envigorate', 'Envigorate', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1027', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1028', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1029', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1030', '            Chongun', '            Chongun', '5', '5', '            Chongun', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1031', 'tiger_might', 'Tiger\'s Might', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1032', 'curse protection', 'Curse Protection', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1033', 'evaluate_opponent', 'Evaluate Opponent', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1034', 'art_of_war', 'Art of War', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1035', 'slaughter', 'Slaughter', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1036', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1037', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1038', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1039', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1040', '                 Do', '                 Do', '5', '5', '                 Do', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1041', 'hear_footstep', 'Hear Footstep', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1042', 'increase_metabolism', 'Increase Metabolism', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1043', 'throw_weapon', 'Throw Weapon', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1044', 'empower', 'Empower', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1045', 'spirit_blade', 'Spirit Blade', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1046', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1047', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1048', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1049', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1050', '        Chung Ryong', '        Chung Ryong', '5', '5', '        Chung Ryong', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1051', 'endure', 'Endure', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1052', 'spot_traps', 'Spot Traps', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1053', 'chungryong_rage', 'Chungryong Rage', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1054', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1055', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1056', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1057', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1058', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1059', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1060', '== Warrior - Grade ==', '== Warrior - Grade ==', '5', '5', '== Warrior - Grade ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1061', 'tiger_slash', 'Tiger Slash', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1062', 'u_gum_swording', 'U gum Swording', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1063', 'chin_baek_hyo_rung', 'Chin Baek Hyo Rung', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1064', 'cho_spirit', 'Cho\'s Spirit', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1065', 'sho_spirit', 'Sho\'s Spirit', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1066', 'cyclone', 'Cyclone', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1067', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1068', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1069', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('1070', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2000', '      == Rogue ==', '      == Rogue ==', '5', '5', '      == Rogue ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2001', 'frisk', 'Frisk', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2002', 'might', 'Might', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2003', 'judge', 'Judge', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2004', 'feral', 'Feral', '1', '2', 'Transform: (c)at/(d)og/(p)ig:', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2005', 'rodent', 'Rodent', '1', '2', 'Transform: (s)quirrel/(r)abbit:', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2006', 'gangrel', 'Gangrel', '1', '2', 'Transform: (f)ox/(w)olf:', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2007', 'beast', 'Beast', '1', '2', 'Transform: (b)ear/(t)iger:', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2008', 'mend_wounds', 'Mend Wounds', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2009', 'seal_wounds', 'Seal Wounds', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2010', 'wolf_fury', 'Wolf\'s Fury', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2011', 'tiger_fury', 'Tiger\'s Fury', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2012', 'shadow_figure', 'Shadow Figure', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2013', 'ignite', 'Ignite', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2014', 'set_trap', 'Set Trap', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2015', 'spy', 'Spy', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2016', 'invisible', 'Invisible', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2017', 'approach', 'Approach', '1', '2', 'Approach to: ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2018', 'ambush', 'Ambush', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2019', 'amnesia', 'Amnesia', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2020', 'return', 'Return', '1', '2', 'Return? (Y/N)', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2021', 'recover', 'Recover', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2022', 'desperate_attack', 'Desperate Attack', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2023', 'summon', 'Summon', '1', '2', 'Summon : ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2024', 'flich', 'Flich', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2025', 'drain', 'Drain', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2026', 'slow', 'Slow', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2027', 'shadow_dance_old', 'Shadow Dance Old', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2028', 'prince_charming', 'Prince Charming', '1', '2', ': >', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2029', 'lethal_strike', 'Lethal Strike', '5', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2030', 'jujak_fire', 'Jujak Fire', '2', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2031', 'jujak_inferno', 'Jujak Inferno', '2', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2032', 'jujak_blaze', 'Jujak Blaze', '2', '2', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2033', 'jujak_abomination', 'Jujak Abomination', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2034', 'hyunmoo_snow', 'Hyunmoo Snow', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2035', 'hyunmoo_deathrain', 'Hyunmoo Deathrain', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2036', 'hyunmoo_blaspheme', 'Hyunmoo Blaspheme', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2037', 'hyun_blizzard', 'Hyun Blizzard', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2038', 'baekho_surge', 'Baekho Surge', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2039', 'baekho_disaster', 'Baekho Disaster', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2040', 'baekho_cataclysm', 'Baekho Cataclysm', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2041', 'baekho_in_hell', 'Baekho In Hell', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2042', 'baekho_cataclysm', 'Baekho Cataclysm', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2043', 'chungryong_ray', 'Chungryong Ray', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2044', 'chung_thunderbolt', 'Chung Thunderbolt', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2045', 'chungryong_slice', 'Chungryong Slice', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2046', 'chungryong_cyclone', 'Chungryong Cyclone', '2', '2', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2047', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2048', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2049', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2050', '     == Merchant ==', '     == Merchant ==', '5', '5', '     == Merchant ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2051', 'dash', 'Dash', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2052', 'fuddle', 'Fuddle', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2053', 'ox_form', 'Ox Form', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2054', 'hostess_form', 'Hostess Form', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2055', 'bekyun_arrow', 'Bekyun Arrow', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2056', 'cutpurse', 'Cutpurse', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2057', 'gamble', 'Gamble', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2058', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2059', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2060', '      == Baekho == ', '      == Baekho == ', '0', '5', '      == Baekho == ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2061', 'dash', 'Dash', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2062', 'peace', 'Peace', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2063', 'baekho_cunning', 'Baekho Cunning', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2064', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2065', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2066', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2067', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2068', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2069', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2070', '         == Spy ==', '         == Spy ==', '0', '5', '         == Spy ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2071', 'seem', 'Seem', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2072', 'hear_footstep', 'Hear Footstep', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2073', 'assess_opponent', 'Assess Opponent', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2074', 'assasinate', 'Assasinate', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2075', 'tranquil_symphony', 'Tranquil Symphony', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2076', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2077', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2078', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2079', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2080', '       == Shadow ==', '       == Shadow ==', '0', '5', '       == Shadow ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2081', 'fuddle', 'Fuddle', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2082', 'shadow', 'Shadow', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2083', 'shade', 'Shade', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2084', 'hear_footstep', 'Hear Footstep', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2085', 'burst', 'Burst', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2086', 'skeleton_form', 'Skeleton Form', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2087', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2088', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2089', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2090', ' == Rogue - Grade ==', ' == Rogue - Grade ==', '0', '5', ' == Rogue - Grade ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2091', 'withenal_strike', 'Withenal Strike', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2092', 'sword_rash', 'Sword Rash', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2093', 'no_move', 'No Move', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2094', 'kimun_art', 'Kimun\'s art', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2095', 'shadow_sword', 'Shadow Sword', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2096', 'hell_shadow', 'Hell Shadow', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2097', 'body_replacement', 'Body Replacement', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2098', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2099', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('2100', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3000', '        == Mage ==', '        == Mage ==', '5', '5', '        == Mage ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3001', 'jujak_fire', 'Jujak Fire', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3002', 'jujak_inferno', 'Jujak Inferno', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3003', 'jujak_blaze', 'Jujak Blaze', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3004', 'jujak_abomination', 'Jujak Abomination', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3005', 'jujak_fire_strom', 'Jujak Fire Strom', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3006', 'hyunmoo_snow', 'Hyunmoo Snow', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3007', 'hyunmoo_deathrain', 'Hyunmoo Deathrain', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3008', 'hyunmoo_blaspheme', 'Hyunmoo Blaspheme', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3009', 'hyun_blizzard', 'Hyun Blizzard', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3010', 'strombringer', 'Strombringer', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3011', 'baekho_surge', 'Baekho Surge', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3012', 'baekho_disaster', 'Baekho Disaster', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3013', 'baekho_cataclysm', 'Baekho Cataclysm', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3014', 'baekho_in_hell', 'Baekho In Hell', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3015', 'baekho_deathsoul', 'Baekho Deathsoul', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3016', 'chungryong_ray', 'Chungryong Ray', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3017', 'chung_thunderbolt', 'Chung Thunderbolt', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3018', 'chungryong_slice', 'Chungryong Slice', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3019', 'chungryong_cyclone', 'Chungryong Cyclone', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3020', 'calamity_of_chungryong', 'Calamity Of Chungryong', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3021', 'return', 'Return', '1', '3', 'Return? (Y/N)', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3022', 'harden_armor', 'Harden Armor', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3023', 'lay_hands', 'Lay Hands', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3024', 'might', 'Might', '5', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3025', 'mend_wounds', 'Mend Wounds', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3026', 'valor', 'Valor', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3027', 'approach', 'Approach', '1', '3', 'Approach to : ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3028', 'relief', 'Relief', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3029', 'purge', 'Purge', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3030', 'recover', 'Recover', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3031', 'summon', 'Summon', '1', '3', 'Summon : ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3032', 'cure_paralysis', 'Cure paralysis', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3033', 'sanctuary', 'Sanctuary', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3034', 'invoke', 'Invoke', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3035', 'heal', 'Heal', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3036', 'remove_curse', 'Remove Curse', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3037', 'venom', 'Venom', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3038', 'vex', 'Vex', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3039', 'blind', 'Blind', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3040', 'paralyze', 'Paralyze', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3041', 'confuse', 'Confuse', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3042', 'sleep', 'Sleep', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3043', 'doze', 'Doze', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3044', 'rejuvenate', 'Rejuvenate', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3045', 'sage_old', 'Sage Old', '1', '3', ':>', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3046', 'hell_fire', 'Hell Fire', '2', '3', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3047', 'jujak_area_lv1', 'Jujak Holyfire', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3048', 'jujak_area_lv2', 'Jujak Fireclaw', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3049', 'jujak_area_lv3', 'Jujak Hellraiser', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3050', 'jujak_area_lv4', 'Jujak Bloodfire', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3051', 'jujak_area_lv5', 'Jujak Massacre', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3052', 'hyunmoo_area_lv1', 'Hyun Deathstrom', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3053', 'hyunmoo_area_lv2', 'Hyun Ice Bomb', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3054', 'hyunmoo_area_lv3', 'Hyun Water Strom', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3055', 'hyunmoo_area_lv4', 'Hyun Death Ice', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3056', 'hyunmoo_area_lv5', 'Water Of Death', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3057', 'baekho_area_lv1', 'Baekho Death Realm', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3058', 'baekho_area_lv2', 'Baekho Revenge', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3059', 'baekho_area_lv3', 'Baekho Bloodline', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3060', 'baekho_area_lv4', 'Lava Of Baekho', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3061', 'baekho_area_lv5', 'Angel Of Death', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3062', 'chungryong_area_lv1', 'Chung Tornado', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3063', 'chungryong_area_lv2', 'Chungryong Typhoon', '5', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3064', 'chungryong_area_lv3', 'Death Lighting', '0', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3065', 'chungryong_area_lv4', 'Chungryong Blast', '0', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3066', 'chungryong_area_lv5', 'Call Of Thunder', '0', '3', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3067', 'invoked', 'Invoked', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3068', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3069', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3070', '       == Jujak == ', '       == Jujak == ', '0', '5', '       == Jujak == ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3071', 'fissure', 'Fissure', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3072', 'lava_surge', 'Lava Surge', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3073', 'gather_spirit', 'Gather Spirit', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3074', 'volcanic_blast', 'Volcanic Blast', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3075', 'jujak_evocation', 'Jujak Evocation', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3076', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3077', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3078', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3079', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3080', '   == Geomancer ==', '   == Geomancer ==', '0', '5', '   == Geomancer ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3081', 'goodearth', 'GoodEarth', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3082', 'green_potion', 'Green Potion', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3083', 'ice_strom', 'Ice Strom', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3084', 'hailstrom', 'HailStrom', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3085', 'deep_sleep', 'Deep Sleep', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3086', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3087', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3088', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3089', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3090', '     == Shaman ==', '     == Shaman ==', '0', '5', '     == Shaman ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3091', 'bless_food', 'Bless Food', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3092', 'bless_drink', 'Bless Drink', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3093', 'restore_spirit', 'Restore Spirit', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3094', 'phoenix_flames', 'Phoenix Flames', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3095', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3096', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3097', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3098', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3099', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3100', '      == Diviner ==', '      == Diviner ==', '0', '5', '      == Diviner ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3101', 'divine_time', 'Divine Time', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3102', 'hear_footstep', 'Hear Footstep', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3103', 'vanish', 'Vanish', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3104', 'darken_fate', 'Darken Fate', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3105', 'seal_fate', 'Seal Fate', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3106', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3107', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3108', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3109', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3110', '  == Mage - Grade ==', '  == Mage - Grade ==', '0', '5', '  == Mage - Grade ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3111', 'regenerate', 'Regenerate', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3112', 'sam_hell', 'Sam Hell', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3113', 'hoche', 'Hoche', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3114', 'bomb_hell', 'Bomb Hell', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3115', 'demon_body', 'Demon Body', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3116', 'angry_waves', 'Angry Waves', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3117', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3118', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3119', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('3120', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4000', '              Poet', '              Poet', '5', '5', '              Poet', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4001', 'jujak_target_lv1', 'Jujak Fire', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4002', 'hyunmoo_target_lv1', 'Hyunmoo Snow', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4003', 'baekho_target_lv1', 'Baekho Surge', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4004', 'chungryong_target_lv1', 'Chunryong Ray', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4005', 'invoke', 'Invoke', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4006', 'recover', 'Recover', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4007', 'purge', 'Purge', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4008', 'harden_armor', 'Harden Armor', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4009', 'vital_spark', 'Vital Spark', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4010', 'sanctuary', 'Sanctuary', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4011', 'remove_curse', 'Remove Curse', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4012', 'barrier', 'Barrier', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4013', 'valor', 'Valor', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4014', 'heal', 'Heal', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4015', 'approach', 'Approach', '1', '4', 'Approach to: ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4016', 'annoint', 'Annoint', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4017', 'return', 'Return', '1', '4', 'Return? (Y/N)', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4018', 'summon', 'Summon', '1', '4', 'Summon : ', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4019', 'remove veil', 'Remove Veil', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4020', 'cure_paralysis', 'Cure Paralysis', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4021', 'steed', 'Steed', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4022', 'revitalize', 'Revitalize', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4023', 'inspiration', 'Inspiration', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4024', 'atone', 'Atone', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4025', 'remedy', 'Remedy', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4026', 'second_sight', 'Second Sight', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4027', 'retribution', 'Retribution', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4028', 'fortify', 'Fortify', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4029', 'inspire', 'Inspire', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4030', 'call_of_the_wild', 'Call of the Wild', '1', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4031', 'scourge', 'Scourge', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4032', 'thunder_touch', 'Thunder Touch', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4033', 'earthquake', 'Earthquake', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4034', 'blockade_human', 'Blockade Human', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4035', 'heaven_kiss', 'Heaven\'s Kiss', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4036', 'harden_body', 'Harden Body', '5', '4', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4037', 'dispell', 'Dispell', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4038', 'flare', 'Flare', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4039', 'water_of_life', 'Water of Life', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4040', 'prince_charming', 'Prince Charming', '1', '4', ':>', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4041', 'ressurection', 'Ressurection', '2', '4', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4042', 'buss_kiss', 'Buss Kiss', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4043', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4044', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4045', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4046', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4047', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4048', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4049', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4050', '       == Druid ==', '       == Druid ==', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4051', 'nature_bloom', ' Nature\'s Bloom', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4052', 'nature_call', ' Nature Call', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4053', 'lighting_strike', ' Lightning Strike', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4054', 'lighting_strom', ' Lightning Storm', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4055', 'heaven_dew', ' Heaven\'s Dew ', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4056', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4057', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4058', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4059', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4060', '        == Monk ==', '        == Monk ==', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4061', 'bless_food', 'Bless Food', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4062', 'bless_drink', 'Bless Drink', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4063', 'awe', 'Awe', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4064', 'summon_monkey', 'Summon Monkey', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4065', 'heaven_dew', 'Heaven\'s Dew', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4066', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4067', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4068', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4069', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4070', '        == Muse ==', '        == Muse ==', '5', '5', '        == Muse ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4071', 'sacred_verse', 'Sacred Verse', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4072', 'lesser_effect', 'Lesser Effect', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4073', 'mad_fox', 'Summon Fox', '2', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4074', 'mad_wolf', 'Summon Wolf', '2', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4075', 'heaven_dew', 'Heaven\'s Dew ', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4076', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4077', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4078', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4079', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4080', '    == Hyun Moo ==', '    == Hyun Moo ==', '5', '5', '    == Hyun Moo ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4082', 'sacred_song', 'Sacred Song', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4083', 'hyunmoo_revival', 'Hyunmoo Revival', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4084', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4085', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4086', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4087', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4088', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4089', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4090', '  == Poet - Grade ==', '  == Poet - Grade ==', '5', '5', '  == Poet - Grade ==', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4091', 'buskiss', 'Bus\'s Kiss', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4092', 'sin_of_life', 'Sin of Life', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4093', 'reflect', 'Reflect', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4094', 'heal_charm', 'Heal Charm', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4095', 'pa_art', 'Pa\'s Art', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4096', 'soul_call', 'Soul Call', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4097', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4098', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4099', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('4100', '', '', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5000', '         == GM ==', '         == GM ==', '0', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5001', 'power_nap', 'Power Nap', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5002', 'bank_access', 'Bank Access', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5003', 'iganinja_sword', 'Iganinja Sword', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5004', 'gm_push', 'GM Push', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5005', 'from_coor', 'From Coor', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5006', 'to_coor', 'To Coor', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5007', 'cr1', 'Chungryong Rage 1', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5008', 'cr2', 'Chungryong Rage 2', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5009', 'cr3', 'Chungryong Rage 3', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5010', 'cr4', 'Chungryong Rage 4', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5011', 'cr5', 'Chungryong Rage 5', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5012', 'gm_res', 'GM Ressurection', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5013', 'blitz_beat', 'Blitz Beat', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5014', 'jadi_barclayz', 'Jadi Barclayz', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5015', 'myvoes', 'mYvoes', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5016', 'sevennz', 'SevennZ', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5017', 'vending_system', 'Vending', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5018', 'monyet_event', 'Monyet Event', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5019', 'monyet_event', 'monyet event', '1', '5', '(a, b, c) :', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5020', 'throw_banana', 'Throw Banana', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5021', 'start_sumo', 'Start Sumo', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5022', 'gm_entangle', 'Gm entangle', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5023', 'necromancer', 'Necromancer', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5024', 'monyet1', 'Monyet', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5025', 'meicia', 'Meicia', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5026', 'minal_aidin', 'Minal Aidin', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5027', 'test_cho', 'Test Cho', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5028', 'great_falcon', 'Great Falcon', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5029', 'wind_walk', 'Wind Walk', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5030', 'powder_trap', 'Powder Trap', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5031', 'check_pws', 'Check Pws', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5032', 'omni', 'Omni Slash', '2', '5', 'Target?', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5033', 'fireworks', 'Fireworks', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5034', 'ss_test', 'SS test', '5', '5', 'coba dulu in game', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5035', 'mass_summon', 'Yuk Kumpul', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5036', 'mass_dance', 'Lets Joget', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5037', 'gm_dispel', 'Super Dispel', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5038', 'backTarget', 'backTarget Test', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5039', 'jadi_ravel', 'Ravel', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5040', 'monyet_edric', 'edric monkey', '5', '5', '', '0', '0', '0', '1');
INSERT INTO `Spells` VALUES ('5041', 'clear_target_reg', 'Clear Target Reg', '2', '5', 'Target?', '0', '0', '0', '1');
